### ISSUE TITLE
Component Organization

### ISSUE THREAD

**Issue by rudeluv** [Foodbeast/universal-es6-redux-react-semantic#3]
Wondering if we should add some folder organization to components. 
## Proposing
- App.js
- Layout.js
- common/
  - DropDown.js
  - FullContent.js
  - Menu.js
  - Page.js
- post/
  - list/
    - PostList.js
    - PostListPage.js
    - PostCard.js
  - details/ 
    - PostDetails.js
    - PostDetailPage.js

Thoughts @christopherabouabdo?

**Comment by christopherabouabdo** [comment]
I like that, might want to include separation for containers/components within those deeper folders. Something like: 
- post/
  - list/
    - components/
    - containers/
  - details/
    - components/
    - containers/

Or containers could just live alongside components since we're designating them in their filenames...
- post/list/
  - PostList.js
  - PostListContainer.js

What do you think?
